version: '2'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /tmp:/uploads
    ports:
     - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"