version: '2'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./celery
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env

  monitor:
    build:
      context: ./celery
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    entrypoint: flower
    command: -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
       - redis

  redis:
    image: redis
    env_file:
      - .env
